--liquibase formatted sql

--changeset tinder4dogs:005-create-chat
--comment: one chat per mutual match, the dog pair stored in canonical (min, max) order
--
-- uq_chat_pair backs idempotent creation at storage level: a duplicate event
-- for the same pair collides here instead of opening a second conversation.
-- ck_chat_pair_order keeps the pair canonical, so both constraints see the
-- same key no matter which dog id arrived first.
CREATE TABLE chat (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dog_a_id        BIGINT NOT NULL,
    dog_b_id        BIGINT NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    last_message_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_chat_dog_a FOREIGN KEY (dog_a_id) REFERENCES dog (id),
    CONSTRAINT fk_chat_dog_b FOREIGN KEY (dog_b_id) REFERENCES dog (id),
    CONSTRAINT uq_chat_pair UNIQUE (dog_a_id, dog_b_id),
    CONSTRAINT ck_chat_pair_order CHECK (dog_a_id < dog_b_id)
);
-- uq_chat_pair only covers lookups where the dog is dog_a_id; a dog whose id is
-- the higher one sits in dog_b_id, which no index covers. Index it so both
-- sides of a pair are queryable.
CREATE INDEX idx_chat_dog_b ON chat (dog_b_id);
--rollback DROP TABLE chat;

--changeset tinder4dogs:006-create-message
--comment: immutable plain-text messages; acceptance order is id order
CREATE TABLE message (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id        BIGINT NOT NULL,
    sender_dog_id  BIGINT NOT NULL,
    text           VARCHAR(2000) NOT NULL,
    accepted_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_message_chat FOREIGN KEY (chat_id) REFERENCES chat (id),
    CONSTRAINT fk_message_dog FOREIGN KEY (sender_dog_id) REFERENCES dog (id)
);
CREATE INDEX idx_message_chat_id_id ON message (chat_id, id);
--rollback DROP TABLE message;
